/* @glint-ng/core — Angular Style Zone UI Library */
/* Public API Surface */

export * from './lib/core/index';
export { GlintButtonComponent } from './lib/button/button.component';
export { GlintCheckboxComponent } from './lib/checkbox/checkbox.component';
export { GlintRadioButtonComponent } from './lib/radio-button/radio-button.component';
export { GlintToggleSwitchComponent } from './lib/toggle-switch/toggle-switch.component';
export { GlintTextareaComponent } from './lib/textarea/textarea.component';
export { GlintBadgeComponent } from './lib/badge/badge.component';
export { GlintTagComponent } from './lib/tag/tag.component';
export { GlintDividerComponent } from './lib/divider/divider.component';
export { GlintInputNumberComponent } from './lib/input-number/input-number.component';
export { GlintCardComponent, GlintCardHeaderDirective, GlintCardSubtitleDirective, GlintCardFooterDirective } from './lib/card/card.component';
export { GlintInputComponent } from './lib/input/input.component';
export { GlintTooltipDirective } from './lib/tooltip/tooltip.directive';
export { GlintTooltipPanelComponent } from './lib/tooltip/tooltip.component';
export { injectGlintDialog } from './lib/dialog/dialog.service';
export type { GlintDialog } from './lib/dialog/dialog.service';
export { GlintDialogRef } from './lib/dialog/dialog-ref';
export { GLINT_DIALOG_DATA } from './lib/dialog/dialog.config';
export type { GlintDialogConfig, GlintDialogPosition } from './lib/dialog/dialog.config';
export { GlintSelectComponent } from './lib/select/select.component';
export { GlintSelectOptionComponent } from './lib/select/select-option.component';
export { GLINT_SELECT } from './lib/select/select.model';
export type { GlintSelectHost, CompareWithFn } from './lib/select/select.model';
export { GlintTabsComponent } from './lib/tabs/tabs.component';
export { GlintTabPanelComponent } from './lib/tabs/tab-panel.component';
export { GlintMenuComponent } from './lib/menu/menu.component';
export type { GlintMenuItem } from './lib/menu/menu-item.model';
export { GlintToastService } from './lib/toast/toast.service';
export { GlintToastComponent } from './lib/toast/toast.component';
export type { GlintToastMessage, GlintToastPosition } from './lib/toast/toast.model';
export { GlintMessageComponent } from './lib/message/message.component';
export { GlintProgressBarComponent } from './lib/progress-bar/progress-bar.component';
export { GlintProgressSpinnerComponent } from './lib/progress-spinner/progress-spinner.component';
export { GlintSkeletonComponent } from './lib/skeleton/skeleton.component';
export { GlintBreadcrumbComponent } from './lib/breadcrumb/breadcrumb.component';
export type { GlintBreadcrumbItem } from './lib/breadcrumb/breadcrumb.component';
export { GlintAccordionComponent } from './lib/accordion/accordion.component';
export { GlintAccordionPanelComponent } from './lib/accordion/accordion-panel.component';
export { GlintAvatarComponent } from './lib/avatar/avatar.component';
export { GlintAvatarGroupComponent } from './lib/avatar/avatar-group.component';
export { GlintChipComponent } from './lib/chip/chip.component';
export { GlintDrawerComponent } from './lib/drawer/drawer.component';
export { GlintPopoverComponent } from './lib/popover/popover.component';
export { GlintToolbarComponent } from './lib/toolbar/toolbar.component';
export { GlintPaginatorComponent } from './lib/paginator/paginator.component';
export type { GlintPageEvent } from './lib/paginator/paginator.component';
export { GlintTableComponent, GlintTableEmptyDirective } from './lib/table/table.component';
export { GlintColumnDirective } from './lib/table/table-column.directive';
export type { GlintColumnAlign } from './lib/table/table-column.directive';
export type { GlintSortEvent } from './lib/table/table.component';
export { GlintPasswordComponent } from './lib/password/password.component';
export { GlintSliderComponent } from './lib/slider/slider.component';
export { GlintConfirmDialogService } from './lib/confirm-dialog/confirm-dialog.service';
export type { GlintConfirmConfig } from './lib/confirm-dialog/confirm-dialog.service';
export { GlintSplitButtonComponent } from './lib/split-button/split-button.component';
export { GlintFieldsetComponent } from './lib/fieldset/fieldset.component';
export { GlintStepperComponent } from './lib/stepper/stepper.component';
export { GlintStepComponent } from './lib/stepper/step.component';
export { GlintStepHeaderComponent } from './lib/stepper/step-header.component';
export { CdkStepperNext, CdkStepperPrevious } from '@angular/cdk/stepper';
export type { StepperSelectionEvent, StepperOrientation } from '@angular/cdk/stepper';
export { GlintTimelineComponent } from './lib/timeline/timeline.component';
export type { GlintTimelineEvent } from './lib/timeline/timeline.component';
export { GlintToggleButtonComponent } from './lib/toggle-button/toggle-button.component';
export { GlintRatingComponent } from './lib/rating/rating.component';
export { GlintListboxComponent } from './lib/listbox/listbox.component';
export { GlintSelectButtonComponent } from './lib/select-button/select-button.component';
export type { SelectButtonOption } from './lib/select-button/select-button.component';
export { GlintInputMaskComponent } from './lib/input-mask/input-mask.component';
export { GlintInputOtpComponent } from './lib/input-otp/input-otp.component';
export { GlintPanelComponent } from './lib/panel/panel.component';
export { GlintInplaceComponent, GlintInplaceDisplayDirective, GlintInplaceContentDirective } from './lib/inplace/inplace.component';
export { GlintFloatLabelComponent } from './lib/float-label/float-label.component';
export { GlintInputGroupComponent, GlintInputGroupAddonDirective } from './lib/input-group/input-group.component';
export { GlintScrollTopComponent } from './lib/scroll-top/scroll-top.component';
export { GlintMeterGroupComponent } from './lib/meter-group/meter-group.component';
export type { GlintMeterItem } from './lib/meter-group/meter-group.component';
export { GlintContextMenuDirective } from './lib/context-menu/context-menu.directive';
export { GlintTieredMenuComponent } from './lib/tiered-menu/tiered-menu.component';
export { GlintMenuBarComponent } from './lib/menubar/menubar.component';
export { GlintPanelMenuComponent } from './lib/panel-menu/panel-menu.component';
export { GlintDockComponent } from './lib/dock/dock.component';
export { GlintCascadeSelectComponent } from './lib/cascade-select/cascade-select.component';
export { GlintSpeedDialComponent } from './lib/speed-dial/speed-dial.component';
export { GlintTreeComponent } from './lib/tree/tree.component';
export { GlintTreeTableComponent } from './lib/tree-table/tree-table.component';
export { GlintTreeTableColumnDirective } from './lib/tree-table/tree-table-column.directive';
export { GlintTreeSelectComponent } from './lib/tree-select/tree-select.component';
export { GlintOrganizationChartComponent } from './lib/organization-chart/organization-chart.component';
export { GlintAutoCompleteComponent } from './lib/autocomplete/autocomplete.component';
export { GlintMultiSelectComponent } from './lib/multiselect/multiselect.component';
export { GlintDatepickerComponent } from './lib/datepicker/datepicker.component';
export { GlintDatepickerDayDirective, type GlintDatepickerDayContext } from './lib/datepicker/datepicker-day.directive';
export { GlintDataViewComponent } from './lib/data-view/data-view.component';
export { GlintScrollerComponent } from './lib/scroller/scroller.component';
export { GlintImageComponent } from './lib/image/image.component';
export { GlintImageCompareComponent } from './lib/image-compare/image-compare.component';
export { GlintCarouselComponent } from './lib/carousel/carousel.component';
export { GlintGalleriaComponent } from './lib/galleria/galleria.component';
export type { GlintGalleriaImage } from './lib/galleria/galleria.component';
export { GlintColorPickerComponent } from './lib/colorpicker/colorpicker.component';
export { GlintKnobComponent } from './lib/knob/knob.component';
export { GlintFileUploadComponent } from './lib/file-upload/file-upload.component';
export { GlintConfirmPopupService } from './lib/confirm-popup/confirm-popup.service';
export type { GlintConfirmPopupConfig } from './lib/confirm-popup/confirm-popup.service';
export { GlintBlockUiComponent } from './lib/block-ui/block-ui.component';
export { GlintOverlayBadgeComponent } from './lib/overlay-badge/overlay-badge.component';
export { GlintOrderListComponent } from './lib/order-list/order-list.component';
export { GlintPickListComponent } from './lib/pick-list/pick-list.component';
export { GlintSplitterComponent, GlintSplitterPanelComponent } from './lib/splitter/splitter.component';
export { GlintScrollPanelComponent } from './lib/scroll-panel/scroll-panel.component';
export { GlintEditorComponent } from './lib/editor/editor.component';
export { GlintShellComponent } from './lib/shell/shell.component';
export { GlintShellSidebarComponent } from './lib/shell/shell-sidebar.component';
export { GlintShellHeaderComponent } from './lib/shell/shell-header.component';
export { GlintShellContentComponent } from './lib/shell/shell-content.component';
export { GLINT_SHELL_SIDEBAR } from './lib/shell/shell.model';
export type { GlintShellSidebarHost } from './lib/shell/shell.model';
export { GlintSearchComponent } from './lib/search/search.component';
export { DARK_ZONE, COMPACT_ZONE, DANGER_ZONE, SOFT_ZONE, DARK_COMPACT_ZONE } from './lib/presets/theme-presets';

// Icon system
export { GlintIconComponent } from './lib/icon/icon.component';
export { GLINT_ICON_REGISTRY, provideGlintIcons } from './lib/icon/icon.registry';
export { GLINT_ICON_CONFIG, provideGlintIconConfig } from './lib/icon/icon.config';
export type { GlintIconConfig } from './lib/icon/icon.config';
export { mapIcons, lucideToSvg } from './lib/icon/map-icons';

// Testing
export { cleanupOverlays, provideGlintTestIcons } from './lib/testing/test-utils';
